system_id: 1001
app_name: csn
app_instance_name: csn_001 
bbf:
  config:
    host: 10.1.8.69
    #host: 127.0.0.1
    port: 9090
    refresh_mode: 1
    refresh_interval: 5000
    refresh_crontab: "*/2 * * * *"
    force: true
