package com.orm;

/**
 * TDoc generated by MyEclipse Persistence Tools
 */

public class Tzuoyestu
{

	private int id;
	private String mingcheng;
	private String fujian;
	private String fujianYuanshiming;
	
	private String shijian_shangchuan;
	private String piyueneirong;
	private String shijian_pinyue;
	private int stu_id;
	
	private Tstu stu;


	public String getFujian()
	{
		return fujian;
	}

	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}

	public Tstu getStu()
	{
		return stu;
	}

	public void setStu(Tstu stu)
	{
		this.stu = stu;
	}

	public String getFujianYuanshiming()
	{
		return fujianYuanshiming;
	}

	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}

	public int getStu_id()
	{
		return stu_id;
	}

	public void setStu_id(int stu_id)
	{
		this.stu_id = stu_id;
	}

	public int getId()
	{
		return id;
	}

	public void setId(int id)
	{
		this.id = id;
	}

	public String getMingcheng()
	{
		return mingcheng;
	}

	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}

	public String getPiyueneirong()
	{
		return piyueneirong;
	}

	public void setPiyueneirong(String piyueneirong)
	{
		this.piyueneirong = piyueneirong;
	}

	public String getShijian_pinyue()
	{
		return shijian_pinyue;
	}

	public void setShijian_pinyue(String shijian_pinyue)
	{
		this.shijian_pinyue = shijian_pinyue;
	}

	public String getShijian_shangchuan()
	{
		return shijian_shangchuan;
	}

	public void setShijian_shangchuan(String shijian_shangchuan)
	{
		this.shijian_shangchuan = shijian_shangchuan;
	}

}