package com.orm;

/**
 * TDoc generated by MyEclipse Persistence Tools
 */

public class Tzuoye
{

	private int id;
	private String mingcheng;
	private String fujian;
	private String fujianYuanshiming;
	
	private String shijian;
	private int tea_id;
	private Ttea tea;
	
	
	public String getFujian()
	{
		return fujian;
	}
	public void setFujian(String fujian)
	{
		this.fujian = fujian;
	}
	public String getFujianYuanshiming()
	{
		return fujianYuanshiming;
	}
	public void setFujianYuanshiming(String fujianYuanshiming)
	{
		this.fujianYuanshiming = fujianYuanshiming;
	}
	
	public int getId()
	{
		return id;
	}
	public void setId(int id)
	{
		this.id = id;
	}
	public String getMingcheng()
	{
		return mingcheng;
	}
	
	public Ttea getTea()
	{
		return tea;
	}
	public void setTea(Ttea tea)
	{
		this.tea = tea;
	}
	public void setMingcheng(String mingcheng)
	{
		this.mingcheng = mingcheng;
	}
	public String getShijian()
	{
		return shijian;
	}
	public void setShijian(String shijian)
	{
		this.shijian = shijian;
	}
	public int getTea_id()
	{
		return tea_id;
	}
	public void setTea_id(int tea_id)
	{
		this.tea_id = tea_id;
	}

	
}